### ISSUE TITLE
Stable null safety release

### ISSUE THREAD

**Issue by LasseRosenow** [dart-lang/os_detect#9]
@athomas 

As flutter 2.0 with stable null safety support was released a few weeks ago, when can we expect this package to ship its null safe version to stable?

**Comment by athomas** [comment]
@natebosch might be able to answer that. I don't see an obvious reason why we couldn't publish a stable version of this package.

**Comment by natebosch** [comment]
No reason not to publish with a stable version now.

**Comment by LasseRosenow** [comment]
@lrhn I think this should be reopened until there really is a stable null safety release on pub.dev

**Comment by lrhn** [comment]
It's released. Thanks!
